### ISSUE TITLE
Compatible with tensorflow v1.x？

### ISSUE THREAD

**Issue by zhangzibin** [persiyanov/skip-thought-tf#1]
Hi, Thanks for your great code.
I go through the code and found it depends on `tf.nn.rnn_cell` and `tf.nn.seq2seq` heavily, which are deprecated in v1.x. I wonder do you have plan to modify the code for tensorflow v1.x?

**Comment by persiyanov** [comment]
@zhangzibin Hi! I wrote this code several months ago (TF version 0.11 - 0.12). Yes, I could move it to version 1.0.x when I have free time (these weekends, for example).

Or you can look at forks of my repo, maybe some of them moved to TF 1.0.x.

**Comment by zhangzibin** [comment]
@persiyanov Thanks for your reply. I've done with it. It simply to replace the different APIs. Btw: I'm using the code to train a meaningful sentence vector. Thanks for you great work.

**Comment by persiyanov** [comment]
@zhangzibin If you could submit a PR it would be perfect!

**Comment by zhangzibin** [comment]
@persiyanov Of course. I'll submit a PR after I make sure the code work.
